const byId=id=>document.getElementById(id),canvas=byId('game'),ctx=canvas.getContext('2d');
const ui={level:byId('levelText'),health:byId('healthText'),healthBar:byId('healthBar'),ammo:byId('ammoText'),mag:byId('magText'),damage:byId('damageText'),enemies:byId('enemyText'),overlay:byId('overlay'),overlayTitle:byId('overlayTitle'),overlayText:byId('overlayText'),start:byId('startButton'),message:byId('message'),shop:byId('shop'),shopCredits:byId('shopCredits'),resources:byId('resources')};
const W=canvas.width,H=canvas.height,GROUND=550,WORLD=3000,keys={}; let game,state,raf,last=0,camera=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function reset(){game={level:1,damage:12,ammo:32,credits:0,potions:0,maxHp:80,magSize:8,mag:8,reloading:0};ui.shop.classList.add('hidden');startLevel()}
function startLevel(){
  state='playing'; ui.overlay.classList.add('hidden');
  const n=5+game.level*2; camera=0;game.levelStart=performance.now();game.mag=game.magSize;game.reloading=0;game.player={x:70,y:GROUND-48,w:28,h:48,vx:0,vy:0,hp:game.maxHp,face:1,onGround:true,shot:0,flash:0,inv:0};
  game.bullets=[];game.enemyBullets=[];game.pickups=[];game.particles=[];game.obstacles=[];game.platforms=[];game.enemies=[];
  for(let i=0;i<6;i++){let x=350+i*430+rnd(-45,45);game.obstacles.push({x,y:GROUND-rnd(42,82),w:rnd(38,60),h:rnd(42,82)});}
  for(let i=0;i<5;i++){game.platforms.push({x:430+i*500+rnd(-50,50),y:GROUND-rnd(110,210),w:rnd(135,190),h:14});}
  for(let i=0;i<n;i++){let platform=Math.random()<.48?game.platforms[Math.floor(Math.random()*game.platforms.length)]:null,x=platform?platform.x+rnd(12,platform.w-38):rnd(380,WORLD-100),y=platform?platform.y-42:GROUND-42;game.enemies.push({x,y,w:27,h:42,hp:22+game.level*14,maxHp:22+game.level*14,dir:Math.random()<.5?-1:1,shot:rnd(30,100),speed:.55+game.level*.1,vy:0,onGround:true,dodge:0});}
  updateUI(); announce(`SECTOR 0${game.level}`,1400);
}
function updateUI(){let hp=game.player?.hp??game.maxHp??80;ui.level.textContent=String(game.level).padStart(2,'0');ui.health.textContent=Math.ceil(hp);ui.healthBar.style.width=`${hp/(game.maxHp||80)*100}%`;ui.ammo.textContent=game.ammo;ui.mag.textContent=game.reloading>0?'RELOAD':`${game.mag} / ${game.magSize}`;ui.damage.textContent=game.damage.toFixed(1);ui.enemies.textContent=game.enemies?.length??0;ui.shopCredits.textContent=game.credits||0;ui.resources.innerHTML=`CREDITS <b>${game.credits||0}</b> · POTIONS <b>${game.potions||0}</b>`;}
function announce(t,ms=900){ui.message.textContent=t;ui.message.classList.add('show');setTimeout(()=>ui.message.classList.remove('show'),ms)}
function shoot(){let p=game.player;if(p.shot>0||game.mag<=0||game.reloading>0){if(game.mag<=0)reload();return}p.shot=13;game.mag--;game.bullets.push({x:p.x+(p.face>0?p.w:-10),y:p.y+18,w:11,h:3,vx:p.face*11});p.flash=4;updateUI()}
function reload(){if(state!=='playing'||game.reloading>0||game.mag===game.magSize||game.ammo<=0)return;game.reloading=55;announce('RELOADING',600);updateUI()}
function usePotion(){if(state!=='playing'||game.potions<1||game.player.hp>=game.maxHp)return;game.potions--;game.player.hp=Math.min(game.maxHp,game.player.hp+35);announce('+35 HEALTH');updateUI()}
function enemyShoot(e){let p=game.player,dx=p.x-e.x,dy=(p.y+20)-(e.y+15),d=Math.hypot(dx,dy);game.enemyBullets.push({x:e.x+13,y:e.y+15,w:7,h:4,vx:dx/d*(3.2+game.level*.25),vy:dy/d*(3.2+game.level*.25),damage:5+(game.level-1)*2});}
function drop(x,y){let r=Math.random();if(r<.7)game.pickups.push({x,y,w:18,h:18,type:r<.43?'ammo':'boost',bob:0});}
function particles(x,y,color,n=7){for(let i=0;i<n;i++)game.particles.push({x,y,vx:rnd(-3,3),vy:rnd(-3,1),life:rnd(12,25),color});}
function update(dt){if(state!=='playing')return;let p=game.player,s=dt/16.67;
  let move=(keys.KeyA?-1:0)+(keys.KeyD?1:0),speed=(keys.ControlLeft||keys.ControlRight)?5.8:3.5;p.vx=move*speed;if(move)p.face=move;
  if(keys.Space&&p.onGround){p.vy=-11;p.onGround=false;keys.Space=false} if(keys.ShiftLeft||keys.ShiftRight)shoot();
  p.vy+=.55*s;p.x=clamp(p.x+p.vx*s,0,WORLD-p.w);let oldBottom=p.y+p.h;p.y+=p.vy*s;p.onGround=false;if(p.y+p.h>=GROUND){p.y=GROUND-p.h;p.vy=0;p.onGround=true}
  for(const o of [...game.obstacles,...game.platforms])if(p.vy>=0&&p.x+p.w>o.x&&p.x<o.x+o.w&&oldBottom<=o.y+5&&p.y+p.h>=o.y){p.y=o.y-p.h;p.vy=0;p.onGround=true}
  camera=clamp(p.x-W*.36,0,WORLD-W);
  p.shot-=s;p.flash-=s;p.inv-=s;if(game.reloading>0){game.reloading-=s;if(game.reloading<=0){let need=game.magSize-game.mag,take=Math.min(need,game.ammo);game.mag+=take;game.ammo-=take;updateUI()}}
  for(const b of game.bullets)b.x+=b.vx*s;
  for(const e of game.enemies){let dist=p.x-e.x;if(Math.abs(dist)<650)e.dir=Math.sign(dist)||e.dir;e.dodge-=s;for(const b of game.bullets){let incoming=(b.vx>0&&b.x<e.x)||(b.vx<0&&b.x>e.x);if(e.dodge<=0&&e.onGround&&incoming&&Math.abs(b.x-e.x)<155&&Math.abs(b.y-(e.y+20))<32){e.vy=-9;e.onGround=false;e.dodge=rnd(60,100);e.dir*=-1;break}}let ahead={x:e.x+(e.dir>0?e.w+4:-10),y:e.y+8,w:8,h:e.h-8};if(e.onGround&&game.obstacles.some(o=>hit(ahead,o)))e.vy=-9.5;e.x=clamp(e.x+e.dir*(e.speed+1.05)*s,170,WORLD-35);e.vy+=.48*s;let eb=e.y+e.h;e.y+=e.vy*s;e.onGround=false;if(e.y+e.h>=GROUND){e.y=GROUND-e.h;e.vy=0;e.onGround=true}for(const o of game.platforms)if(e.vy>=0&&e.x+e.w>o.x&&e.x<o.x+o.w&&eb<=o.y+5&&e.y+e.h>=o.y){e.y=o.y-e.h;e.vy=0;e.onGround=true}e.shot-=s;if(e.shot<=0&&Math.abs(e.x-p.x)<720){enemyShoot(e);e.shot=rnd(62,105)-game.level*5}}
  for(const b of game.enemyBullets){b.x+=b.vx*s;b.y+=b.vy*s;if(hit(b,p)&&p.inv<=0){p.hp-=b.damage;p.inv=28;b.dead=true;particles(p.x+14,p.y+20,'#ff654f');updateUI();if(p.hp<=0)end(false)}}
  for(const b of game.bullets)for(const e of game.enemies)if(!b.dead&&!e.dead&&hit(b,e)){b.dead=true;e.hp-=game.damage;particles(b.x,b.y,'#d7ff3f',5);if(e.hp<=0){e.dead=true;drop(e.x,e.y);particles(e.x+14,e.y+20,'#ff654f',14)}}
  for(const b of [...game.bullets,...game.enemyBullets])if([...game.obstacles,...game.platforms].some(o=>hit(b,o))){b.dead=true;particles(b.x,b.y,'#758a7c',3)}
  for(const q of game.pickups){q.bob+=.06*s;if(keys.KeyC&&Math.hypot(p.x-q.x,p.y-q.y)<65){q.dead=true;if(q.type==='ammo'){game.ammo+=10;announce('+10 AMMO')}else{game.damage=+(game.damage+6.7).toFixed(1);announce('WEAPON +6.7')}updateUI()}}
  game.bullets=game.bullets.filter(b=>!b.dead&&b.x>-20&&b.x<WORLD+20);game.enemyBullets=game.enemyBullets.filter(b=>!b.dead&&b.x>-20&&b.x<WORLD+20&&b.y<H);game.pickups=game.pickups.filter(q=>!q.dead);game.enemies=game.enemies.filter(e=>!e.dead);game.particles.forEach(q=>{q.x+=q.vx*s;q.y+=q.vy*s;q.vy+=.12;q.life-=s});game.particles=game.particles.filter(q=>q.life>0);
  if(!game.enemies.length){updateUI();state='transition';setTimeout(()=>{if(game.level===5)end(true);else goHome()},900);announce('SECTOR CLEAR',900)}updateUI();
}
function goHome(){let seconds=(performance.now()-game.levelStart)/1000,bonus=Math.max(10,Math.round(90-seconds)),reward=40+game.level*15+bonus;game.credits+=reward;game.level++;state='home';ui.overlay.classList.remove('hidden');ui.shop.classList.remove('hidden');ui.overlayTitle.innerHTML='SUPPLY<br><em>BASE</em>';ui.overlayText.textContent=`Sector cleared in ${seconds.toFixed(1)}s. You earned ${reward} credits, including a ${bonus} speed bonus.`;ui.start.innerHTML='NEXT SECTOR <span>→</span>';updateUI()}
function buy(type){if(state!=='home')return;let costs={damage:40,health:45,mag:35,potion:25},cost=costs[type];if(game.credits<cost){announce('NOT ENOUGH CREDITS');return}game.credits-=cost;if(type==='damage')game.damage+=4;if(type==='health')game.maxHp+=15;if(type==='mag')game.magSize+=2;if(type==='potion')game.potions++;updateUI()}
function end(win){state='ended';ui.shop.classList.add('hidden');ui.overlay.classList.remove('hidden');ui.overlayTitle.innerHTML=win?'MISSION<br><em>COMPLETE</em>':'YOU WERE<br><em>LOST</em>';ui.overlayText.textContent=win?'All five sectors are clear. The last light holds—for now.':'The sector remains hostile. Redeploy and finish the mission.';ui.start.innerHTML='RESTART <span>↻</span>'}
function draw(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#14241c');g.addColorStop(1,'#0a100d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-camera,0);
  ctx.fillStyle='#1d3026';for(let i=0;i<35;i++){let x=i*93+(i%2)*30+camera*.55,h=80+(i*47)%170;ctx.fillRect(x,GROUND-h-50,55,h)}ctx.fillStyle='#0e1712aa';ctx.fillRect(camera,GROUND-55,W,55);
  ctx.strokeStyle='#263c30';ctx.lineWidth=1;for(let x=0;x<WORLD;x+=55){ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+30,H);ctx.stroke()}ctx.fillStyle='#26382e';ctx.fillRect(0,GROUND,WORLD,H-GROUND);ctx.fillStyle='#66806f';ctx.fillRect(0,GROUND,WORLD,3);
  for(const o of game?.platforms||[]){ctx.fillStyle='#34463b';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#758a7c';ctx.fillRect(o.x,o.y,o.w,3);ctx.fillStyle='#1a251f';for(let x=o.x+12;x<o.x+o.w;x+=28)ctx.fillRect(x,o.y+14,5,25)}
  for(const o of game?.obstacles||[]){ctx.fillStyle='#202d27';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#3b4b42';ctx.strokeRect(o.x+.5,o.y+.5,o.w-1,o.h-1);ctx.fillStyle='#d7ff3f';ctx.fillRect(o.x+7,o.y+9,3,14)}
  for(const q of game?.pickups||[]){let y=q.y+Math.sin(q.bob)*4;ctx.fillStyle=q.type==='ammo'?'#f2d584':'#d7ff3f';ctx.fillRect(q.x,y,18,14);ctx.fillStyle='#111';ctx.font='bold 10px Inter';ctx.fillText(q.type==='ammo'?'A':'+',q.x+5,y+11)}
  for(const e of game?.enemies||[]){ctx.fillStyle='#7b3029';ctx.fillRect(e.x,e.y+9,e.w,e.h-9);ctx.fillStyle='#e66754';ctx.fillRect(e.x+5,e.y,e.w-10,15);ctx.fillStyle='#141a16';ctx.fillRect(e.x+(e.dir>0?20:-9),e.y+18,16,5);ctx.fillStyle='#39211d';ctx.fillRect(e.x,e.y-8,e.w,3);ctx.fillStyle='#ff654f';ctx.fillRect(e.x,e.y-8,e.w*(e.hp/e.maxHp),3)}
  if(game?.player){let p=game.player;ctx.globalAlpha=p.inv>0&&Math.floor(p.inv/3)%2?0.35:1;ctx.fillStyle='#b6c5bc';ctx.fillRect(p.x,p.y+10,p.w,p.h-10);ctx.fillStyle='#d7ff3f';ctx.fillRect(p.x+5,p.y,p.w-10,16);ctx.fillStyle='#121713';ctx.fillRect(p.x+(p.face>0?20:-14),p.y+20,22,6);if(p.flash>0){ctx.fillStyle='#fff9b0';ctx.beginPath();ctx.arc(p.x+(p.face>0?44:-14),p.y+23,8,0,7);ctx.fill()}ctx.globalAlpha=1}
  ctx.fillStyle='#d7ff3f';for(const b of game?.bullets||[])ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#ff654f';for(const b of game?.enemyBullets||[])ctx.fillRect(b.x,b.y,b.w,b.h);for(const q of game?.particles||[]){ctx.globalAlpha=q.life/25;ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,3,3)}ctx.globalAlpha=1;ctx.restore();
}
function loop(t){let dt=Math.min(34,t-last||16);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(['Space','ShiftLeft','ShiftRight','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!e.repeat&&e.code==='KeyV')reload();if(!e.repeat&&e.code==='KeyH')usePotion();if(!e.repeat&&e.code==='KeyE')ui.resources.classList.toggle('show')});addEventListener('keyup',e=>keys[e.code]=false);ui.start.addEventListener('click',()=>state==='home'?startLevel():reset());document.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();buy(b.dataset.buy)}));game={enemies:[],maxHp:80,ammo:0,mag:0,magSize:8};draw();loop(0);
