const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const ui = { coins:document.getElementById('coins'), lives:document.getElementById('lives'), wave:document.getElementById('wave'), message:document.getElementById('message'), waveButton:document.getElementById('waveButton'), speedButton:document.getElementById('speedButton'), upgrade:document.getElementById('upgradeContent'), modal:document.getElementById('modal'), modalIcon:document.getElementById('modalIcon'), modalTitle:document.getElementById('modalTitle'), modalText:document.getElementById('modalText') };
const path = [{x:-25,y:130},{x:190,y:130},{x:190,y:380},{x:455,y:380},{x:455,y:205},{x:710,y:205},{x:710,y:465},{x:980,y:465}];
const plots = [{x:90,y:205},{x:118,y:435},{x:285,y:300},{x:320,y:440},{x:365,y:112},{x:510,y:305},{x:555,y:465},{x:605,y:135},{x:755,y:112},{x:775,y:335},{x:865,y:520}];
const config = { broccoli:{name:'Broccoli',emoji:'🥦',cost:4,range:126,damage:3,rate:480,projectile:'#8be24c'}, pepper:{name:'Pepper',emoji:'🌶️',cost:8,range:108,damage:7,rate:840,projectile:'#ff7a46'} };
let state, selectedType = 'broccoli', selectedTower = null, lastTime = 0;

function reset(){ state={coins:10,lives:3,wave:1,towers:[],enemies:[],shots:[],running:false,spawned:0,spawnTotal:0,spawnTimer:0,gameOver:false,speed:1,gameTime:0}; selectedTower=null; selectedType='broccoli'; document.querySelectorAll('.tower-choice').forEach(b=>b.classList.toggle('selected',b.dataset.type===selectedType)); ui.modal.classList.add('hidden'); setMessage('Choose a plant, then click a garden plot.'); updateUI(); updateUpgrade(); }
function updateUI(){ ui.coins.textContent=state.coins;ui.lives.textContent=state.lives;ui.wave.textContent=state.wave;ui.speedButton.textContent=`Speed: ${state.speed===1?'Normal':state.speed+'×'}`; const done=state.gameOver||state.wave>10; ui.waveButton.disabled=state.running||done; ui.waveButton.textContent=state.running?'Wave in progress…':state.wave>10?'All waves cleared!':`Start wave ${state.wave}`; }
function setMessage(text){ui.message.textContent=text;}
function choose(type){selectedType=type;selectedTower=null;document.querySelectorAll('.tower-choice').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));updateUpgrade();setMessage(`Selected ${config[type].name}. Click an empty garden plot to plant it.`);}
function placeAt(plot){if(state.running&&state.enemies.length){setMessage('You can still plant during a wave!');} if(state.towers.some(t=>t.plot===plot))return setMessage('That plot already has a defender.'); const c=config[selectedType];if(state.coins<c.cost)return setMessage(`You need ${c.cost-state.coins} more coin${c.cost-state.coins===1?'':'s'} for ${c.name}.`);state.coins-=c.cost;const tower={type:selectedType,x:plot.x,y:plot.y,plot,level:1,lastShot:0,priority:'first'};state.towers.push(tower);selectedTower=tower;setMessage(`${c.name} planted! Its default target priority is First.`);updateUI();updateUpgrade();}
function startWave(){state.running=true;state.spawned=0;state.spawnTotal=5+state.wave*2;state.spawnTimer=0;setMessage(`Wave ${state.wave}: ${state.spawnTotal} bugs are approaching!`);updateUI();}
function spawn(){const hp=10+state.wave*5;state.enemies.push({x:path[0].x,y:path[0].y,segment:0,hp,maxHp:hp,speed:36+state.wave*3,reward:2+Math.floor(state.wave/3),r:15,slow:0});}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function endWave(){state.running=false;if(state.lives<=0)return; if(state.wave===10){state.wave=11;state.gameOver=true;showModal('🏆','Garden saved!','You defended the treasure through all 10 bug waves. The garden celebrates your victory!');}else{state.wave++;setMessage(`Wave cleared! Spend your coins, then start wave ${state.wave}.`);}updateUI();}
function showModal(icon,title,text){ui.modalIcon.textContent=icon;ui.modalTitle.textContent=title;ui.modalText.textContent=text;ui.modal.classList.remove('hidden');}
function tick(dt,time){dt*=state.speed;state.gameTime+=dt;if(!state.gameOver){ if(state.running){state.spawnTimer+=dt;if(state.spawned<state.spawnTotal&&state.spawnTimer>650){state.spawnTimer=0;state.spawned++;spawn();}}
  for(const enemy of state.enemies){let target=path[enemy.segment+1];let speed=enemy.speed*(enemy.slow>0?.62:1);enemy.slow=Math.max(0,enemy.slow-dt);let dx=target.x-enemy.x,dy=target.y-enemy.y,d=Math.hypot(dx,dy);if(d<speed*dt/1000){enemy.x=target.x;enemy.y=target.y;enemy.segment++;if(enemy.segment>=path.length-1)enemy.escaped=true;}else{enemy.x+=dx/d*speed*dt/1000;enemy.y+=dy/d*speed*dt/1000;}}
  for(const tower of state.towers){const c=config[tower.type];const range=c.range+(tower.type==='pepper'?(tower.level-1)*52:0);const inRange=state.enemies.filter(e=>!e.escaped&&distance(tower,e)<=range);const target=pickTarget(inRange,tower);if(target&&state.gameTime-tower.lastShot>c.rate){tower.lastShot=state.gameTime;state.shots.push({x:tower.x,y:tower.y,target,damage:c.damage+(tower.type==='broccoli'?(tower.level-1)*2:0),color:c.projectile,pepper:tower.type==='pepper'});}}
  for(const shot of state.shots){if(!shot.target||shot.target.hp<=0)shot.done=true;else{let dx=shot.target.x-shot.x,dy=shot.target.y-shot.y,d=Math.hypot(dx,dy),v=420*dt/1000;if(d<=v){shot.target.hp-=shot.damage;if(shot.pepper)shot.target.slow=320;shot.done=true;}else{shot.x+=dx/d*v;shot.y+=dy/d*v;}}}
  const slain=state.enemies.filter(e=>e.hp<=0);if(slain.length){state.coins+=slain.reduce((n,e)=>n+e.reward,0);setMessage(`Great shot! You earned ${slain.reduce((n,e)=>n+e.reward,0)} coin${slain.reduce((n,e)=>n+e.reward,0)===1?'':'s'}.`);}
  const escaped=state.enemies.filter(e=>e.escaped);if(escaped.length){state.lives-=escaped.length;setMessage(`A bug reached the chest! ${Math.max(state.lives,0)} lives remain.`);if(state.lives<=0){state.lives=0;state.gameOver=true;state.running=false;showModal('🐛','The bugs found the treasure','Three bugs reached the chest. Plant a stronger garden and try again!');}}
  state.enemies=state.enemies.filter(e=>e.hp>0&&!e.escaped);state.shots=state.shots.filter(s=>!s.done);if(state.running&&state.spawned===state.spawnTotal&&state.enemies.length===0)endWave();updateUI(); }
 draw();requestAnimationFrame(now=>{const elapsed=Math.min(35,now-lastTime||16);lastTime=now;tick(elapsed,now);});}
function draw(){ctx.clearRect(0,0,960,600);ctx.fillStyle='#91d878';ctx.fillRect(0,0,960,600);ctx.strokeStyle='#6bb660';ctx.lineWidth=2;for(let i=15;i<960;i+=55){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i-150,600);ctx.stroke();}
 ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#c89550';ctx.lineWidth=58;ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);for(const p of path.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle='#f0d491';ctx.lineWidth=44;ctx.stroke();
 ctx.font='39px sans-serif';ctx.textAlign='center';ctx.fillText('🎁',914,477);ctx.font='12px sans-serif';ctx.fillStyle='#694324';ctx.fillText('TREASURE',914,512);
 for(const p of plots){ctx.beginPath();ctx.arc(p.x,p.y,24,0,Math.PI*2);ctx.fillStyle='#3f8b4d';ctx.fill();ctx.strokeStyle='#d3f1a4';ctx.lineWidth=2;ctx.stroke();}
 for(const t of state.towers){const c=config[t.type];let range=c.range+(t.type==='pepper'?(t.level-1)*52:0);if(t===selectedTower){ctx.beginPath();ctx.arc(t.x,t.y,range,0,Math.PI*2);ctx.fillStyle='rgba(250,255,220,.18)';ctx.fill();ctx.strokeStyle='rgba(38,104,51,.45)';ctx.setLineDash([5,5]);ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);}ctx.font='34px sans-serif';ctx.textAlign='center';ctx.fillText(c.emoji,t.x,t.y+12);if(t.level>1){ctx.fillStyle='#fff4a5';ctx.beginPath();ctx.arc(t.x+16,t.y-19,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5e4a18';ctx.font='bold 10px sans-serif';ctx.fillText(t.level,t.x+16,t.y-15);}}
 for(const s of state.shots){ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fillStyle=s.color;ctx.fill();}
 for(const e of state.enemies){ctx.font='29px sans-serif';ctx.textAlign='center';ctx.fillText('🐛',e.x,e.y+9);ctx.fillStyle='#4d2f26';ctx.fillRect(e.x-16,e.y-23,32,5);ctx.fillStyle='#e85b48';ctx.fillRect(e.x-16,e.y-23,32*Math.max(0,e.hp/e.maxHp),5);}
}
function pickTarget(enemies,tower){if(!enemies.length)return null;const progress=e=>e.segment+distance(e,path[e.segment])/Math.max(1,distance(path[e.segment],path[e.segment+1]));return enemies.sort((a,b)=>{if(tower.priority==='first')return progress(b)-progress(a);if(tower.priority==='last')return progress(a)-progress(b);if(tower.priority==='strong')return b.hp-a.hp;if(tower.priority==='weak')return a.hp-b.hp;return distance(tower,a)-distance(tower,b);})[0];}
function updateUpgrade(){if(!selectedTower){ui.upgrade.innerHTML='<p class="muted">Click a planted defender to inspect and upgrade it.</p>';return;}const t=selectedTower,c=config[t.type],cost=t.type==='broccoli'?6:5;const effect=t.type==='broccoli'?'+2 damage':'+'+52+' attack reach';const maxed=t.level>=2;ui.upgrade.innerHTML=`<div class="upgrade-title"><span>${c.emoji}</span><div><b>${c.name} · Level ${t.level} / 2</b><div class="muted" style="margin:1px 0 0">${t.type==='broccoli'?c.damage+(t.level-1)*2+' damage':c.range+(t.level-1)*52+' reach'}</div></div></div><p class="upgrade-detail">Target priority</p><select class="target-select" id="targetPriority"><option value="first" ${t.priority==='first'?'selected':''}>First — nearest to treasure</option><option value="last" ${t.priority==='last'?'selected':''}>Last — farthest from treasure</option><option value="strong" ${t.priority==='strong'?'selected':''}>Strongest — highest health</option><option value="weak" ${t.priority==='weak'?'selected':''}>Weakest — lowest health</option><option value="closest" ${t.priority==='closest'?'selected':''}>Closest — nearest to this plant</option></select><p class="upgrade-detail">${maxed?'<b>Maximum level reached.</b>':`Upgrade: <b>${effect}</b> for ${cost} coins.`}</p><button class="upgrade-button" id="upgradeButton" ${state.coins<cost||maxed?'disabled':''}>${maxed?'Max level':`Upgrade for 🪙 ${cost}`}</button>`;document.getElementById('targetPriority')?.addEventListener('change',ev=>{t.priority=ev.target.value;setMessage(`${c.name} will now target ${ev.target.options[ev.target.selectedIndex].text.split(' — ')[0].toLowerCase()} bugs.`);});document.getElementById('upgradeButton')?.addEventListener('click',()=>{if(state.coins<cost||t.level>=2)return;state.coins-=cost;t.level++;setMessage(`${c.name} upgraded to level ${t.level}!`);updateUI();updateUpgrade();});}
canvas.addEventListener('click',ev=>{if(state.gameOver)return;const rect=canvas.getBoundingClientRect(),x=(ev.clientX-rect.left)*canvas.width/rect.width,y=(ev.clientY-rect.top)*canvas.height/rect.height;const tower=state.towers.find(t=>Math.hypot(t.x-x,t.y-y)<28);if(tower){selectedTower=tower;updateUpgrade();setMessage(`${config[tower.type].name} selected. Upgrade it from the menu.`);return;}const plot=plots.find(p=>Math.hypot(p.x-x,p.y-y)<28);if(plot)placeAt(plot);else setMessage('Choose one of the marked green garden plots.');});
document.querySelectorAll('.tower-choice').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.type)));ui.waveButton.addEventListener('click',startWave);ui.speedButton.addEventListener('click',()=>{state.speed=state.speed===3?1:state.speed+1;setMessage(`Game speed: ${state.speed===1?'Normal':state.speed+'×'}.`);updateUI();});document.getElementById('restartButton').addEventListener('click',reset);reset();requestAnimationFrame(t=>{lastTime=t;tick(0,t);});
