(() => {
  'use strict';
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = s => document.querySelector(s);
  const ui = {hud:$('#hud'),start:$('#startScreen'),shop:$('#shopScreen'),end:$('#endScreen'),cross:$('#crosshair'),toast:$('#toast'),pBar:$('#playerBar'),eBar:$('#enemyBar'),pHp:$('#playerHp'),eHp:$('#enemyHp'),eName:$('#enemyName'),round:$('#roundLabel'),weapon:$('#weaponName'),ammo:$('#ammoText'),timer:$('#shopTimer'),cards:$('#weaponCards'),hit:$('#hitMarker'),flash:$('#damageFlash')};
  const TAU=Math.PI*2, FOV=Math.PI/3, MAP_W=16, MAP_H=16;
  const weapons=[
    {name:'Viper Revolver',tag:'PRECISION',damage:36,rate:420,mag:6,reload:1050,spread:.012,color:'#dfff5a',desc:'Heavy, accurate shots. Best for patient aim.'},
    {name:'Riot SMG',tag:'PRESSURE',damage:13,rate:105,mag:22,reload:1350,spread:.045,color:'#59e6ff',desc:'Rapid fire that shreds walls and close targets.'},
    {name:'Breach Shotgun',tag:'BURST',damage:12,pellets:7,rate:720,mag:5,reload:1450,spread:.11,color:'#ff9d4d',desc:'Seven-pellet blast. Devastating up close.'}
  ];
  const enemyNames=['Rookie','Scout','Ranger','Vandal','Warden','Hunter','Phantom','Reaper','War Machine','The Champion'];
  let state='menu',round=1,player,enemy,map=[],weapon=weapons[0],ammo=6,keys={},mouse={x:640,y:360},last=0,lastShot=0,reloading=false,shopInterval,toastTimer,zBuffer=[],tracers=[];
  const foliage=[
    {x:2,y:2.2,t:'tree',s:1.15},{x:5.8,y:2.1,t:'tree',s:.9},{x:9.6,y:2.2,t:'tree',s:1.1},{x:13.5,y:5.5,t:'tree',s:1.05},
    {x:2.1,y:5.5,t:'tree',s:.92},{x:13.3,y:12.8,t:'tree',s:1.2},{x:5.5,y:13.4,t:'tree',s:.88},{x:10.3,y:13.4,t:'tree',s:1},
    {x:3.2,y:7.8,t:'bush',s:.8},{x:5.7,y:5.3,t:'bush',s:.7},{x:10.4,y:5.6,t:'bush',s:.8},{x:12.4,y:8.7,t:'bush',s:.75},
    {x:5.3,y:11.2,t:'bush',s:.68},{x:10.8,y:11.4,t:'bush',s:.82},{x:7.4,y:2.4,t:'bush',s:.65},{x:8.7,y:13.3,t:'bush',s:.72}
  ];

  function baseMap(){
    const m=Array.from({length:MAP_H},(_,y)=>Array.from({length:MAP_W},(_,x)=>(x===0||y===0||x===15||y===15)?9:0));
    [[4,3],[4,4],[4,5],[11,3],[11,4],[11,5],[3,10],[4,10],[5,10],[10,10],[11,10],[12,10],[7,6],[8,6],[7,9],[8,9]].forEach(([x,y])=>m[y][x]=1);
    [[6,3],[9,3],[2,7],[13,8],[6,12],[9,12]].forEach(([x,y])=>m[y][x]=2);
    return m;
  }
  const wallHp=new Map();
  function startGame(){round=1;player={x:2.5,y:13.2,a:-Math.PI/2,hp:100}; weapon=weapons[0]; ammo=weapon.mag; ui.start.classList.remove('shown');ui.end.classList.remove('shown');ui.hud.classList.remove('hidden');ui.cross.style.display='block';startRound();}
  function startRound(){state='playing';map=baseMap();wallHp.clear();for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++)if(map[y][x]===2)wallHp.set(`${x},${y}`,55+round*8);player.x=2.5;player.y=13.2;player.a=-Math.PI/2;const hp=70+round*18;enemy={x:13.2,y:2.5,hp,maxHp:hp,speed:.55+round*.065,damage:4+round*1.45,fireRate:1150-round*62,lastFire:performance.now()+800,strafe:1,strafeAt:0};ammo=weapon.mag;reloading=false;updateHud();showToast(`DUEL ${round} — ${enemyNames[round-1]}`,1300);}
  function angleDiff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b));}
  function solid(x,y){const gx=Math.floor(x),gy=Math.floor(y);return !map[gy]||map[gy][gx]>0;}
  function clearLine(x1,y1,x2,y2){const d=Math.hypot(x2-x1,y2-y1),n=Math.ceil(d*18);for(let i=2;i<n;i++){const t=i/n;if(solid(x1+(x2-x1)*t,y1+(y2-y1)*t))return false;}return true;}
  function tryMove(obj,nx,ny){const r=.22;if(!solid(nx+r,obj.y)&&!solid(nx-r,obj.y))obj.x=nx;if(!solid(obj.x,ny+r)&&!solid(obj.x,ny-r))obj.y=ny;}
  function update(dt,now){if(state!=='playing')return;let dx=0,dy=0;const ca=Math.cos(player.a),sa=Math.sin(player.a),sp=2.65*dt;if(keys.w){dx+=ca;dy+=sa}if(keys.s){dx-=ca;dy-=sa}if(keys.a){dx+=sa;dy-=ca}if(keys.d){dx-=sa;dy+=ca}const l=Math.hypot(dx,dy)||1;tryMove(player,player.x+dx/l*sp,player.y+dy/l*sp);
    const turn=((mouse.x/canvas.clientWidth)-.5)*2;player.a+=Math.sign(turn)*Math.pow(Math.abs(turn),1.35)*dt*4.8;
    if(keys[' ']&&!reloading)shoot(now);
    tracers=tracers.filter(t=>now-t.born<420);
    updateEnemy(dt,now);
  }
  function updateEnemy(dt,now){const dx=player.x-enemy.x,dy=player.y-enemy.y,dist=Math.hypot(dx,dy),los=clearLine(enemy.x,enemy.y,player.x,player.y);if(now>enemy.strafeAt){enemy.strafe=Math.random()<.5?-1:1;enemy.strafeAt=now+700+Math.random()*900}const ang=Math.atan2(dy,dx),desired=4.5-round*.13;let mx=0,my=0;if(dist>desired){mx+=Math.cos(ang);my+=Math.sin(ang)}else if(dist<2.4){mx-=Math.cos(ang);my-=Math.sin(ang)}mx+=Math.cos(ang+Math.PI/2)*enemy.strafe*.55;my+=Math.sin(ang+Math.PI/2)*enemy.strafe*.55;const l=Math.hypot(mx,my)||1;tryMove(enemy,enemy.x+mx/l*enemy.speed*dt,enemy.y+my/l*enemy.speed*dt);if(los&&dist<10&&now-enemy.lastFire>enemy.fireRate){enemy.lastFire=now;const accuracy=.42+round*.045-Math.min(.22,dist*.018);if(Math.random()<accuracy)hurtPlayer(enemy.damage+(Math.random()*3));}}
  function shoot(now){if(now-lastShot<weapon.rate)return;if(ammo<=0){reload();return}lastShot=now;ammo--;updateHud();const aimAngle=player.a+((mouse.x/canvas.clientWidth)-.5)*FOV;tracers.push({x:player.x,y:player.y,a:aimAngle,born:now,color:weapon.color});let hit=false;const pellets=weapon.pellets||1;for(let p=0;p<pellets;p++){const a=aimAngle+(Math.random()-.5)*weapon.spread*2;hit=traceBullet(a,weapon.damage)||hit}if(hit){ui.hit.classList.remove('show');void ui.hit.offsetWidth;ui.hit.classList.add('show')}if(ammo===0)setTimeout(reload,180);}
  function traceBullet(a,damage){const ex=enemy.x-player.x,ey=enemy.y-player.y,proj=ex*Math.cos(a)+ey*Math.sin(a),perp=Math.abs(ex*Math.sin(a)-ey*Math.cos(a));let wallDist=20,wx,wy;for(let t=.15;t<20;t+=.06){const x=player.x+Math.cos(a)*t,y=player.y+Math.sin(a)*t,gx=Math.floor(x),gy=Math.floor(y);if(map[gy]?.[gx]>0){wallDist=t;wx=gx;wy=gy;break}}if(proj>0&&proj<wallDist&&perp<.27){enemy.hp=Math.max(0,enemy.hp-damage);updateHud();if(enemy.hp<=0)winRound();return true}if(wx!==undefined&&map[wy][wx]===2){const k=`${wx},${wy}`,hp=(wallHp.get(k)||1)-damage;wallHp.set(k,hp);if(hp<=0){map[wy][wx]=0;wallHp.delete(k);showToast('COVER DESTROYED',650)}}return false;}
  function reload(){if(reloading||ammo===weapon.mag||state!=='playing')return;reloading=true;showToast('RELOADING…',weapon.reload);setTimeout(()=>{if(state==='playing'){ammo=weapon.mag;reloading=false;updateHud()}},weapon.reload);}
  function hurtPlayer(n){player.hp=Math.max(0,player.hp-n);ui.flash.classList.remove('show');void ui.flash.offsetWidth;ui.flash.classList.add('show');updateHud();if(player.hp<=0)finish(false);}
  function winRound(){if(state!=='playing')return;if(round===10){finish(true);return}state='shop';keys[' ']=false;ui.shop.classList.add('shown');ui.cross.style.display='none';buildShop();let t=12;ui.timer.textContent=t;shopInterval=setInterval(()=>{t--;ui.timer.textContent=t;if(t<=0){clearInterval(shopInterval);closeShop()}},1000);}
  function buildShop(){const choices=[...weapons].sort(()=>Math.random()-.5);ui.cards.innerHTML='';choices.forEach(w=>{const c=document.createElement('article');c.className='weapon-card'+(w===weapon?' selected':'');c.innerHTML=`<small>${w.tag}</small><h3>${w.name}</h3><p>${w.desc}</p><dl><div><dt>DAMAGE</dt><dd>${w.pellets?`${w.damage} × ${w.pellets}`:w.damage}</dd></div><div><dt>MAGAZINE</dt><dd>${w.mag}</dd></div></dl>`;c.onclick=()=>{weapon=w;document.querySelectorAll('.weapon-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');setTimeout(closeShop,350)};ui.cards.append(c)});}
  function closeShop(){if(state!=='shop')return;clearInterval(shopInterval);ui.shop.classList.remove('shown');round++;player.hp=Math.min(100,player.hp+28);ui.cross.style.display='block';startRound();}
  function finish(win){state='ended';keys[' ']=false;clearInterval(shopInterval);ui.hud.classList.add('hidden');ui.cross.style.display='none';ui.end.classList.add('shown');$('#endEyebrow').textContent=win?'ARENA CONQUERED':'RUN ENDED';$('#endTitle').textContent=win?'CHAMPION':'DEFEATED';$('#endCopy').textContent=win?'You survived all ten duels. The arena belongs to you.':`You reached duel ${round} of 10. Adjust your loadout and try again.`;}
  function updateHud(){ui.pBar.style.width=`${player.hp}%`;ui.eBar.style.width=`${Math.max(0,enemy.hp/enemy.maxHp*100)}%`;ui.pHp.textContent=Math.ceil(player.hp);ui.eHp.textContent=Math.ceil(enemy.hp);ui.eName.textContent=enemyNames[round-1];ui.round.textContent=`${round} / 10`;ui.weapon.textContent=weapon.name.toUpperCase();ui.weapon.style.color=weapon.color;ui.ammo.textContent=reloading?'RELOADING':`${ammo} / ${weapon.mag}`;}
  function showToast(msg,ms=800){ui.toast.textContent=msg;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),ms);}

  function castRay(a){const cs=Math.cos(a),sn=Math.sin(a);for(let d=.02;d<24;d+=.025){const x=player.x+cs*d,y=player.y+sn*d,gx=Math.floor(x),gy=Math.floor(y),cell=map[gy]?.[gx]||0;if(cell)return{d,x,y,cell,gx,gy};}return{d:24,cell:9,x:0,y:0};}
  function render(){const w=canvas.width,h=canvas.height;const sky=ctx.createLinearGradient(0,0,0,h*.56);sky.addColorStop(0,'#75abc0');sky.addColorStop(.72,'#b8d4c5');sky.addColorStop(1,'#d7dfb2');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.56);ctx.fillStyle='#49694d';ctx.beginPath();ctx.moveTo(0,h*.47);for(let x=0;x<=w;x+=w/8)ctx.lineTo(x,h*(.38+Math.sin(x*.009)*.035));ctx.lineTo(w,h*.58);ctx.lineTo(0,h*.58);ctx.fill();const floor=ctx.createLinearGradient(0,h*.52,0,h);floor.addColorStop(0,'#567047');floor.addColorStop(1,'#172419');ctx.fillStyle=floor;ctx.fillRect(0,h*.52,w,h*.48);ctx.fillStyle='rgba(197,231,112,.08)';for(let y=h*.58;y<h;y+=36)ctx.fillRect(0,y,w,1);if(!player)return;
    const cols=320,sw=w/cols;zBuffer.length=cols;for(let i=0;i<cols;i++){const a=player.a-FOV/2+(i/cols)*FOV,r=castRay(a),d=r.d*Math.cos(a-player.a);zBuffer[i]=d;const wh=Math.min(h*1.6,h/d),top=h/2-wh/2;let base=r.cell===9?[54,76,58]:r.cell===2?[181,190,156]:[78,98,76];const edge=Math.abs((r.x%1)-.5)>.48||Math.abs((r.y%1)-.5)>.48;const shade=Math.max(.26,1-d/18)*(edge?.72:1);ctx.fillStyle=`rgb(${base.map(v=>Math.floor(v*shade)).join(',')})`;ctx.fillRect(i*sw,top,sw+1,wh);if(r.cell===2&&wallHp.has(`${r.gx},${r.gy}`)){ctx.fillStyle=`rgba(30,20,14,${.18+Math.sin((r.x+r.y)*21)*.08})`;ctx.fillRect(i*sw,top+wh*.38,sw+1,2)}}renderFoliage();renderEnemy();renderTracers();renderWeapon();}
  function projectPoint(x,y){const dx=x-player.x,dy=y-player.y,d=Math.hypot(dx,dy),rel=angleDiff(Math.atan2(dy,dx),player.a);if(Math.abs(rel)>FOV*.62)return null;const sx=canvas.width*(.5+rel/FOV),col=Math.max(0,Math.min(319,Math.floor(sx/canvas.width*320)));if(d>(zBuffer[col]||99)+.25)return null;return{sx,d};}
  function renderFoliage(){const ordered=[...foliage].sort((a,b)=>Math.hypot(b.x-player.x,b.y-player.y)-Math.hypot(a.x-player.x,a.y-player.y));for(const f of ordered){const p=projectPoint(f.x,f.y);if(!p)continue;const size=Math.min(canvas.height,canvas.height/p.d*f.s);ctx.save();ctx.translate(p.sx,canvas.height/2);if(f.t==='tree'){ctx.fillStyle='#654c32';ctx.fillRect(-size*.055,-size*.08,size*.11,size*.48);ctx.fillStyle='#264f2d';for(const [ox,oy,r] of [[0,-.28,.24],[-.17,-.16,.2],[.17,-.15,.21],[0,-.03,.23]]){ctx.beginPath();ctx.arc(size*ox,size*oy,size*r,0,TAU);ctx.fill()}ctx.fillStyle='rgba(117,157,62,.55)';ctx.beginPath();ctx.arc(-size*.08,-size*.28,size*.11,0,TAU);ctx.fill()}else{ctx.fillStyle='#315b30';for(const [ox,oy,r] of [[-.16,.25,.18],[.04,.2,.24],[.22,.27,.16]]){ctx.beginPath();ctx.arc(size*ox,size*oy,size*r,0,TAU);ctx.fill()}ctx.fillStyle='#6c8d42';ctx.fillRect(-size*.18,size*.15,size*.3,size*.04)}ctx.restore();}}
  function renderTracers(){const now=performance.now();for(const t of tracers){const travel=Math.min(7,(now-t.born)*.022),x=t.x+Math.cos(t.a)*travel,y=t.y+Math.sin(t.a)*travel,p=projectPoint(x,y);if(!p)continue;const r=Math.max(3,16/p.d);ctx.save();ctx.shadowBlur=16;ctx.shadowColor=t.color;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.sx,canvas.height/2,r,0,TAU);ctx.fill();ctx.strokeStyle=t.color;ctx.lineWidth=r*.8;ctx.beginPath();ctx.moveTo(p.sx,canvas.height/2);ctx.lineTo(p.sx-Math.sin(angleDiff(t.a,player.a))*28,canvas.height/2+8);ctx.stroke();ctx.restore();}}
  function renderEnemy(){if(!enemy||enemy.hp<=0)return;const dx=enemy.x-player.x,dy=enemy.y-player.y,dist=Math.hypot(dx,dy),rel=angleDiff(Math.atan2(dy,dx),player.a);if(Math.abs(rel)>FOV*.7)return;const sx=canvas.width*(.5+rel/FOV),size=Math.min(canvas.height*1.2,canvas.height/dist*.84),col=Math.floor(sx/canvas.width*320);if(dist>(zBuffer[col]||99)+.2)return;const x=sx-size*.34,y=canvas.height/2-size*.55;ctx.save();ctx.translate(sx,y);const armor=Math.min(1,(round-1)/9);ctx.fillStyle='#151a18';ctx.fillRect(-size*.14,size*.16,size*.28,size*.4);ctx.fillStyle=`rgb(${95+armor*75},${112-armor*30},${98-armor*22})`;ctx.fillRect(-size*.18,size*.18,size*.36,size*.28);ctx.fillStyle='#c3a285';ctx.beginPath();ctx.arc(0,size*.08,size*.12,0,TAU);ctx.fill();ctx.fillStyle=round>5?'#d94d43':'#272e2a';ctx.fillRect(-size*.13,0,size*.26,size*.07);ctx.fillStyle='#090b0a';ctx.fillRect(size*.1,size*.27,size*.36,size*.055);ctx.fillStyle='#27302b';ctx.fillRect(-size*.17,size*.45,size*.12,size*.32);ctx.fillRect(size*.05,size*.45,size*.12,size*.32);ctx.restore();}
  function renderWeapon(){if(state!=='playing')return;const w=canvas.width,h=canvas.height,bob=(keys.w||keys.a||keys.s||keys.d)?Math.sin(performance.now()*.012)*6:0;ctx.save();ctx.translate(w*.5,h*.87+bob);ctx.fillStyle='#141816';ctx.fillRect(-60,-15,120,100);ctx.fillStyle=weapon.color;ctx.globalAlpha=.75;ctx.fillRect(-28,-28,56,18);ctx.fillStyle='#303a34';ctx.globalAlpha=1;ctx.fillRect(-20,-82,40,65);ctx.fillStyle='#0b0e0c';ctx.fillRect(-10,-110,20,35);ctx.restore();}
  function resize(){const d=Math.min(1.5,devicePixelRatio||1);canvas.width=Math.floor(innerWidth*d);canvas.height=Math.floor(innerHeight*d);mouse.x=innerWidth/2;mouse.y=innerHeight/2;}
  function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt,now);render();requestAnimationFrame(loop)}
  addEventListener('resize',resize);addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(k===' ')e.preventDefault();if(k===' '&&state==='playing')shoot(performance.now());if(k==='r')reload()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;ui.cross.style.left=`${e.clientX-15}px`;ui.cross.style.top=`${e.clientY-15}px`});addEventListener('blur',()=>{keys={}});$('#startBtn').onclick=startGame;$('#restartBtn').onclick=startGame;resize();requestAnimationFrame(loop);
})();
