const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score'),livesEl=document.getElementById('lives'),timeEl=document.getElementById('time'),bestEl=document.getElementById('bestScore'),startScreen=document.getElementById('startScreen'),resultScreen=document.getElementById('resultScreen'),finalScoreEl=document.getElementById('finalScore'),resultTitle=document.getElementById('resultTitle'),resultMessage=document.getElementById('resultMessage'),resultEyebrow=document.getElementById('resultEyebrow'),resultIcon=document.getElementById('resultIcon');
const fruits=[{emoji:'🍎',color:'#e85f59',size:38},{emoji:'🍊',color:'#f3a14b',size:39},{emoji:'🍉',color:'#ef6963',size:44},{emoji:'🍋',color:'#f5c94b',size:37},{emoji:'🍓',color:'#ed6170',size:34},{emoji:'🥝',color:'#85b858',size:38},{emoji:'🍑',color:'#f19a78',size:39}];
let W=900,H=555,objects=[],particles=[],trail=[],score=0,lives=3,best=Number(localStorage.getItem('fruitSliceBest')||0),running=false,last=0,spawnClock=0,timeLeft=60,combo=0;bestEl.textContent=best;
function resize(){const ratio=Math.min(window.devicePixelRatio||1,2),box=canvas.getBoundingClientRect();W=box.width;H=box.height;canvas.width=W*ratio;canvas.height=H*ratio;ctx.setTransform(ratio,0,0,ratio,0,0)}window.addEventListener('resize',resize);resize();
function reset(){objects=[];particles=[];trail=[];score=0;lives=3;timeLeft=60;combo=0;spawnClock=0;updateHud()}
function start(){reset();running=true;startScreen.classList.add('hidden');resultScreen.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function finish(reason){running=false;if(score>best){best=score;localStorage.setItem('fruitSliceBest',best);bestEl.textContent=best}finalScoreEl.textContent=score;resultEyebrow.textContent=reason==='lives'?'TOO MANY ROCKS':"TIME'S UP";resultTitle.textContent=score>=20?'水果大师！':score>=8?'切得漂亮！':'再来一局？';resultMessage.textContent=reason==='lives'?'石头很硬，但你可以更小心一点。':'这一轮你一共切到了这些水果。';resultIcon.textContent=score>=20?'🏆':score>=8?'🍓':'🍐';resultScreen.classList.remove('hidden')}
function updateHud(){scoreEl.textContent=score;timeEl.textContent=Math.ceil(timeLeft);livesEl.textContent='♥ '.repeat(lives)+'♡ '.repeat(3-lives)}
function spawn(){const isRock=Math.random()<.2,data=isRock?{emoji:'🪨',color:'#667277',size:40}:fruits[Math.floor(Math.random()*fruits.length)];objects.push({x:50+Math.random()*(W-100),y:H+55,vx:(Math.random()-.5)*1.1,vy:-10-Math.random()*3.5,gravity:.16+Math.random()*.04,spin:(Math.random()-.5)*.08,angle:0,size:data.size,data,rock:isRock,sliced:false})}
function burst(x,y,color){for(let i=0;i<12;i++)particles.push({x,y,vx:(Math.random()-.5)*5,vy:(Math.random()-.7)*5,life:1,color})}
function segmentDistance(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1;if(dx===0&&dy===0)return Math.hypot(px-x1,py-y1);const t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/(dx*dx+dy*dy)));return Math.hypot(px-(x1+t*dx),py-(y1+t*dy))}
function sliceAt(x1,y1,x2=x1,y2=y1){if(!running)return;let hit=false;objects.forEach(o=>{if(o.sliced)return;if(segmentDistance(o.x,o.y,x1,y1,x2,y2)<o.size*.82){o.sliced=true;hit=true;combo++;if(o.rock){score--;lives--;combo=0;burst(o.x,o.y,'#667277');if(lives<=0)finish('lives')}else{score++;burst(o.x,o.y,o.data.color)}updateHud()}});if(hit)trail.push({x:x2,y:y2,life:1})}
function pointer(e){const r=canvas.getBoundingClientRect(),x=(e.clientX??e.touches[0].clientX)-r.left,y=(e.clientY??e.touches[0].clientY)-r.top,from=trail.length?trail[trail.length-1]:{x,y};trail.push({x,y,life:1});sliceAt(from.x,from.y,x,y)}
canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);pointer(e)});
function update(dt){if(!running)return;timeLeft-=dt/1000;spawnClock-=dt;if(spawnClock<=0){spawn();if(Math.random()>.5)spawn();spawnClock=Math.max(460,850-timeLeft*4)}objects.forEach(o=>{o.x+=o.vx*dt/16;o.y+=o.vy*dt/16;o.vy+=o.gravity*dt/16;o.angle+=o.spin*dt/16});objects=objects.filter(o=>o.y<H+80&&!o.sliced);particles.forEach(p=>{p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.vy+=.08*dt/16;p.life-=dt/700});particles=particles.filter(p=>p.life>0);trail.forEach(t=>t.life-=dt/250);trail=trail.filter(t=>t.life>0);updateHud();if(timeLeft<=0)finish('time')}
function draw(){ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#dff2e7');bg.addColorStop(1,'#c9e5d7');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#b6d8c8';ctx.lineWidth=1;for(let x=20;x<W;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3+p.life*3,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;objects.forEach(o=>{if(o.sliced)return;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.angle);ctx.font=(o.size*1.45)+'px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#5b7b6d55';ctx.shadowBlur=10;ctx.fillText(o.data.emoji,0,0);ctx.restore()});if(trail.length>1){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#fff';ctx.shadowColor='#fff';ctx.shadowBlur=10;ctx.lineWidth=5;ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore()}}
function loop(now){const dt=Math.min(40,now-last);last=now;update(dt);draw();if(running)requestAnimationFrame(loop)}
document.getElementById('startButton').onclick=start;document.getElementById('playAgainButton').onclick=start;document.getElementById('restartButton').onclick=start;reset();draw();
